apiVersion: batch/v1
kind: Job
metadata:
  name: bookinfo
spec:
  template:
    spec:
      containers:
      - name: bookinfo
        image: k8s.gcr.io/busybox
        command: ["/bin/sh",  "-c", "ls /etc/config && ls /root"]
        volumeMounts:
        - name: bookinfo
          mountPath: /etc/config
        - name: kube
          mountPath: /root
      volumes:
        - name: bookinfo
          configMap:
            name: bookinfo
        - name: kube
          configMap:
            name: kube
      restartPolicy: Never
  backoffLimit: 4
# kubectl create configmap bookinfo --from-file=/usr/local/bin/bookinfo.sh
# kubectl create configmap kube --from-file=${HOME}/.kube/config
# kubectl apply -n bookinfo -f bookinfo.yaml
# kubectl logs
