FROM pytorch/pytorch AS build
WORKDIR /workspace
ADD https://raw.githubusercontent.com/pytorch/tutorials/master/beginner_source/blitz/cifar10_tutorial.py /workspace
RUN pip install ipywidgets matplotlib
RUN /opt/conda/bin/python3 /workspace/cifar10_tutorial.py

FROM python:3 as production
WORKDIR /tmp
COPY --from=build /workspace/cifar_net.pth .
ADD learn.py /tmp/
CMD ["/bin/sleep", "3600"]
# python3 /tmp/learn.py