apiVersion: batch/v1
kind: Job
metadata:
  name: bookinfo
spec:
  template:
    spec:
      containers:
      - name: bookinfo
        image: bitnami/kubectl:latest
        command: ["/bin/sh",  "-c", "sleep 3600"]
        volumeMounts:
        - name: bookinfo
          mountPath: /etc/config
        - name: kube
          mountPath: /.kube
        - name: deployment
          mountPath: /tmp
        - name: mtls
          mountPath: /tmp
        - name: gateway
          mountPath: /istio-1.6.2/samples/bookinfo/networking/
      volumes:
        - name: bookinfo
          configMap:
            name: bookinfo
        - name: kube
          configMap:
            name: kube
        - name: deployment
          configMap:
            name: deployment
        - name: mtls
          configMap:
            name: mtls
        - name: gateway
          configMap:
            name: gateway
      restartPolicy: Never
  backoffLimit: 4
# kubectl create configmap bookinfo --from-file=/usr/local/bin/bookinfo.sh
# kubectl create configmap kube --from-file=${HOME}/.kube/config
# kubectl apply -n bookinfo -f bookinfo.yaml
# kubectl logs
