apiVersion: batch/v1
kind: Job
metadata:
  name: bookinfo
spec:
  template:
    spec:
      containers:
      - name: bookinfo
        image: ubuntu
        command: ["bash ",  ""]
      restartPolicy: Never
  backoffLimit: 4
# kubectl create configmap bookinfo --from-file=/usr/local/bin/bookinfo.sh
# kubectl apply -n ???? -f bookinfo.yaml
