apiVersion: batch/v1
kind: Job
metadata:
  name: load
spec:
  template:
    spec:
      hostNetwork: true
      containers:
      - name: load
        image: bitnami/kubectl:latest
        command: ["/bin/bash", "/etc/config/load.sh"]
        volumeMounts:
        - name: load
          mountPath: /etc/config
        - name: kube
          mountPath: /root
      volumes:
        - name: load
          configMap:
            name: load
        - name: kube
          configMap:
            name: kube
      restartPolicy: Never
  backoffLimit: 4
