apiVersion: batch/v1
kind: Job
metadata:
  name: load
spec:
  template:
    spec:
      containers:
      - name: load
        image: bitnami/kubectl:latest
        command: ["/bin/sh", "-c", "sleep 3600"]
        volumeMounts:
        - name: load
          mountPath: /etc/config
        - name: kube
          mountPath: /root
      volumes:
        - name: load
          configMap:
            name: load
        - name: kube
          configMap:
            name: kube
      restartPolicy: Never
  backoffLimit: 4
# kubectl create configmap bookinfo --from-file=/usr/local/bin/bookinfo.sh
# kubectl create configmap kube --from-file=${HOME}/.kube/config
# kubectl apply -n bookinfo -f bookinfo.yaml
# kubectl logs
